version: '3.7'

services:

  my-app:
    container_name: sales
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true